### ISSUE TITLE
portability: no getentropy(), fallback to /dev/urandom?

### ISSUE THREAD

**Issue by schmonz** [janmojzis/tlswrapper#6]
In [ced8620](https://github.com/janmojzis/tlswrapper/commit/ced86207a4e1490cc32b598bf16c159daa2eca3a) you swapped out the implementation of `randombytes()` from using `/dev/urandom` to calling `getentropy()`. This breaks the build on at least one platform where I'd want to use tlswrapper.

Would it be possible to continue providing the old implementation as a fallback, perhaps as a compile-time `#define` so that nobody gets it by mistake?

**Comment by janmojzis** [comment]
fixed here: https://github.com/janmojzis/tlswrapper/pull/8

**Comment by schmonz** [comment]
Looks good and I've applied this to pkgsrc/security/tlswrapper. Thanks!
