### ISSUE TITLE
confusion about license

### ISSUE THREAD

**Issue by kapouer** [janmojzis/tlswrapper#9]
Hi,

"public domain" is tricky, because it works differently depending on the country.
See [this page](https://en.wikipedia.org/wiki/Public_domain_in_the_United_States) to scare you.

To avoid falling on the wrong side of the law,  it's much easier to explicitely set a license and copyright.
I suggest WTFPL if you want the bare minimum, or MIT/Expat, or BSD-3-clause, that last one protects against authors names reuse.

**Comment by janmojzis** [comment]
LICENCE updated. I've used same variant LICENCE from tinyssh https://github.com/janmojzis/tinyssh/blob/master/LICENCE
